services:
  bot:
    build: .
    env_file: .env
    restart: always
    ports:
      - "8089:8080"
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - default