services:
  bot:
    image: zhukovsd/it-mentor-community-bot:main
    env_file: .env.prod
    restart: always
    depends_on:
      - database
    
  database:
    image: postgres
    env_file: .env.prod
    restart: always
