services:
  bot:
    image: zhukovsd/it-mentor-community-bot:main
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      PROJECTS_REVIEWS_COLLECTION_CHAT_ID: ${PROJECTS_REVIEWS_COLLECTION_CHAT_ID}
      ADD_PROJECT_ALLOWED_USER_IDS: ${ADD_PROJECT_ALLOWED_USER_IDS}
      JSON_KEY_GOOGLE_API: ${JSON_KEY_GOOGLE_API}
      ADDED_PROJECTS_SPREADSHEET_ID: ${ADDED_PROJECTS_SPREADSHEET_ID}
      INTERVIEW_COLLECTION_SPREADSHEET_ID: ${INTERVIEW_COLLECTION_SPREADSHEET_ID}
      SEARCH_INTERVIEW_QUESTIONS_COMMAND_CHAT_IDS: ${SEARCH_INTERVIEW_QUESTIONS_COMMAND_CHAT_IDS}
      INTERVIEW_PREP_SITE_REPO_OWNER: ${INTERVIEW_PREP_SITE_REPO_OWNER}
      INTERVIEW_PREP_SITE_REPO_NAME: ${INTERVIEW_PREP_SITE_REPO_NAME}
      GITHUB_COMMUNITY_BOT_ACCESS_TOKEN: ${GITHUB_COMMUNITY_BOT_ACCESS_TOKEN}
      QUESTIONS_POPULARITY_UPDATE_ALLOWED_USER_IDS: ${QUESTIONS_POPULARITY_UPDATE_ALLOWED_USER_IDS}
    restart: always
    depends_on:
      - database
    
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
