services:
  bot:
    image: zhukovsd/it-mentor-community-bot:main
    env_file: .env.prod
    restart: always
    depends_on:
      - database
    networks:
      - default
      - local-stack_net
    
  database:
    image: postgres
    env_file: .env.prod
    restart: always

networks:
  local-stack_net:
    external: true
    name: local-stack_default
