SUMMARY_SHEET = 1  # Сводный лист

FIRST_QUESTION_ROW_INDEX = 4
QUESTION_ID_COL_INDEX = 0
QUESTION_COL_INDEX = 2
QUESTION_POPULRATIY_COL_INDEX = 3

FIRST_INTERVIEW_COL_INDEX = 4
INTERVIEW_NAME_ROW_INDEX = 0
INTERVIEW_LINK_ROW_INDEX = 1
