PROJECTS_SHEET = 0
REVIEWS_SHEET = 1

FIRST_PROJECT_ROW_INDEX = 1

PROJECT_PERIOD_COL_INDEX = 0
PROJECT_PROJECT_NAME_COL_INDEX = 1
PROJECT_LANGUAGE_COL_INDEX = 2
PROJECT_REPO_NAME_COL_INDEX = 3
PROJECT_REPO_LINK_COL_INDEX = 4
PROJECT_AUTHOR_NAME_COL_INDEX = 5
PROJECT_AUTHOR_LINK_COL_INDEX = 6

FIRST_REVIEW_ROW_INDEX = 1

REVIEW_PERIOD_COL_INDEX = 0
REVIEW_PROJECT_NAME_COL_INDEX = 1
REVIEW_LANGUAGE_COL_INDEX = 2
REVIEW_REPO_LINK_COL_INDEX = 3
REVIEW_REVIEW_TYPE_COL_INDEX = 4
REVIEW_REVEIW_LINK_COL_INDEX = 5
REVIEW_AUTHOR_NAME_COL_INDEX = 6
REVIEW_AUTHOR_TG_NICK_COL_INDEX = 7
REVIEW_AUTHOR_TG_LINK_COL_INDEX = 8
