PROJECT_HANGMAN = "hangman"
PROJECT_SIMULATION = "simulation"
PROJECT_CURRENCY_EXCHANGE = "currency-exchange"
PROJECT_TENNIS_SCOREBOARD = "tennis-scoreboard"
PROJECT_WEATHER_VIEWER = "weather-viewer"
PROJECT_CLOUD_FILE_STORAGE = "cloud-file-storage"
PROJECT_TASK_TRACKER = "task-tracker"

PROJECT_NAMES: list[str] = [
    PROJECT_HANGMAN,
    PROJECT_SIMULATION,
    PROJECT_CURRENCY_EXCHANGE,
    PROJECT_TENNIS_SCOREBOARD,
    PROJECT_WEATHER_VIEWER,
    PROJECT_CLOUD_FILE_STORAGE,
    PROJECT_TASK_TRACKER,
]
